### ISSUE TITLE
registerCommands only works once

### ISSUE THREAD

**Issue by moeinrahimi** [froala/vue-froala-wysiwyg#61]
so i put this example  in mounted 
``` javascript
$.FroalaEditor.DefineIcon('buttonIcon', { NAME: 'star'})
 
// Define a button.
$.FroalaEditor.RegisterCommand('myButton', {
  // Button title.
  title: 'My Button',
 
  // Specify the icon for the button.
  // If this option is not specified, the button name will be used.
  icon: 'buttonIcon',
 
  // Save the button action into undo stack.
  undo: true,
 
  // Focus inside the editor before the callback.
  focus: true,
 
  // Show the button on mobile or not.
  showOnMobile: true,
 
  // Refresh the buttons state after the callback.
  refreshAfterCallback: true,
 
  // Called when the button is hit.
  callback: function () {
    // The current context is the editor instance.
    console.log (this.html.get());
  },
 
  // Called when the button state might have changed.
  refresh: function ($btn) {
    // The current context is the editor instance.
    console.log (this.selection.element());
  }
})
```
it only works  when you are coming from previous page , refreshing and opening the page directly won't work, i'm using nuxt.

**Comment by pochocho** [comment]
Hello, I'm having a similar issue, I have multiple instances of froala with a custom button. all of them with different conditions to make them render or not. The issue is that if I remove the first froala instance from the page (changing the v-if condition)  all the other instances' toolbar buttons stop working.

For what I can see it appears to be an issue with the destroy functionality if I manually destroy any instance besides the first one, all other instances' toolbar buttons work just fine. It only breaks when destroying the first instance on the page with the custom button.

Any help would be appreciated.
